// BlueprintGeneratedClass AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C
// Size: 0x30 (Inherited: 0x30)
struct UAresBlueprintFunctionLibrary_C : UBlueprintFunctionLibrary {

	void IsClassDefaultObject(struct UObject* Object, struct UObject* __WorldContext, bool& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C.IsClassDefaultObject // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x33d1d60
	void IsUsingLimitedLoading(struct UObject* __WorldContext, bool& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C.IsUsingLimitedLoading // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x33d1d60
	void IsSoftReferenceLoaded(struct TSoftObjectPtr<UObject> , struct UObject* __WorldContext, bool& bLoaded); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C.IsSoftReferenceLoaded // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x33d1d60
	void (struct TArray<struct F>& , struct UObject* __WorldContext, struct TArray<struct TSoftObjectPtr<UObject>>& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (enum class EWeaponStatsFeature Feature, struct UObject* __WorldContext, struct TArray<struct FText>& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x33d1d60
	void (enum class EWeaponStatsFeature Feature, struct UObject* __WorldContext, struct FText& Text); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (enum class EWeaponAltFireDisplayType AltFireType, struct UObject* __WorldContext, struct FText& Text); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (enum class EWallPenetrationDisplayType , struct UObject* __WorldContext, struct FText& Text); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (enum class EWeaponFireModeDisplayType , struct UObject* __WorldContext, struct FText& Text); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (enum class NonVerbalCommTypesEnum , struct UObject* __WorldContext, struct FText& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (enum class NonVerbalCommTypesEnum , struct UObject* __WorldContext, struct FText& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (enum class ECalloutSuperRegion SuperRegion, struct UObject* __WorldContext, struct FText& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x33d1d60
	void (struct FVector Start, struct FVector End, enum class ETraceTypeQuery TraceChannel, struct TArray<struct AActor*>& ActorsToIgnore, bool , struct UObject* __WorldContext, bool& NewParam, struct TArray<struct FHitResult>& OutHit); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct AActor* Actor, struct UObject* __WorldContext, float& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x33d1d60
	void (struct FVector OriginLocation, struct FVector , float Distance, float , float , struct UObject* __WorldContext, struct FVector& Location); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct FVector Location, struct UObject* __WorldContext, float& Distance, float& , float& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct AShooterCharacter* ShooterCharacter, struct TArray<struct AActor*>& ActorsToIgnore, struct FVector , struct UObject* __WorldContext, bool& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct UObject* __WorldContext); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct AShooterCharacter* , struct UObject* __WorldContext); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct FVector , struct AShooterCharacter* Character, struct FRotator , struct UObject* __WorldContext, struct FVector& OutPosition, bool& , struct FName& FailureReason); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct FVector Origin, struct FVector Direction, float Distance, struct AShooterCharacter* , float , struct UObject* __WorldContext, struct FVector& EndPos); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct AActor* Actor, struct FVector Force, struct UObject* __WorldContext, bool& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct TArray<struct UMaterialInterface*>& , struct USkeletalMeshComponent* SkeletalMeshComponent, struct UObject* __WorldContext); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct USkeletalMeshComponent* SkeletalMesh, struct UMaterialInstance* OverrideMaterial, struct UObject* __WorldContext, struct TArray<struct UMaterialInterface*>& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void AresActorIsAliveAndValid(struct AActor* , struct UObject* __WorldContext, bool& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C.AresActorIsAliveAndValid // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x33d1d60
	void (struct AShooterCharacter* ShooterCharacter, struct UObject* __WorldContext, bool& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x33d1d60
	void (struct FVector , struct FVector , float , struct FVector , struct UObject* __WorldContext, bool& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x33d1d60
	void (int32_t& NewParam, struct UObject* __WorldContext); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct TArray<struct F>& , bool Reverse, struct UObject* __WorldContext, struct TArray<struct FVector>& VectorArray); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|HasDefaults|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (struct TArray<struct FVector>& , struct FVector StartPos, float Distance, int32_t StartIndex, struct UObject* __WorldContext, struct FVector& Position, int32_t& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (float , float , struct FVector StartPos, struct FVector , struct AActor* Actor, struct TArray<struct AActor*>& IgnoreActors, float , float , float , struct UObject* __WorldContext, bool& , struct FVector& , enum class & Result); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent) // @ game+0x33d1d60
	void (float Value, int32_t , struct UObject* __WorldContext, int32_t& ); // Function AresBlueprintFunctionLibrary.AresBlueprintFunctionLibrary_C. // (Static|Public|HasOutParms|BlueprintCallable|BlueprintEvent|BlueprintPure) // @ game+0x33d1d60
};

